name: CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  coninuous-deployment:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    if: github.ref == 'refs/heads/main'
    steps:

      # Step 1
      - name: configureawscredentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::001969182821:role/Github_Actions_Role
          aws-region: us-east-1
      # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment --application-name ourcity_website --deployment-group-name ourcity_website_deployment_g --deployment-config-name CodeDeployDefault.OneAtATime --github-location repository=${{ github.repository }},commitId=${{ github.sha }}